DROP TABLE IF EXISTS RECIPES;
/*
CREATE SCHEMA RECIPES;
USE `RECIPES` ;


ENGINE=InnoDB
AUTO_INCREMENT = 1;
*/
CREATE TABLE IF NOT EXISTS RECIPES (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `food_type` VARCHAR(10) DEFAULT NULL,
  `order_count` INT(11) DEFAULT NULL,
   `date_created` VARCHAR(50) DEFAULT NULL,
  `instructions` VARCHAR(500) DEFAULT NULL,
  `ingredients` VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (`id`)
) 